/*
 * DO NOT MODIFY.
 * This file was generated by ms_gen_mvxv_h.py
 */
#define MVXV_HEAD_VER   "2"
#define MVXV_LIB_TYPE   "##"
#define MVXV_CHIP_ID    "I2"
#define MVXV_CHANGELIST "ge318f3e"
#define MVXV_COMP_ID    "KL_LX318####"
#define MVXV_EXT        "[BR:I2_master]"
